### ISSUE TITLE
Using VCR for testing coverage

### ISSUE THREAD

**Issue by Dynnammo** [vvaezian/metabase_api_python#39]
**Context**
Currently, the testing suite is based on a database setup private to @vvaezian . When adding new endpoint or helper functions, we can't run it locally (or it implies heavy setup) to be sure that it accomplishes what we want.

**Feature**
The [Ruby wrapper of Metabase](https://github.com/shimoju/metabase-ruby) uses a gem called VCR that has an interesting way of working : we register APIs calls made with the wrapper against a Metabase instance in YAML / JSON files. When running the test, instead of running it against a Metabase instance, it uses the APIs calls previously registered to check the results.

While it may seem a bit huge as a work to do, the quoted wrapper has currently 34 registered "cassettes" that covers most of the endpoints currently developed in `metabase_api_python` 

**Roadmap**
- [ ] Add VCRpy and [pytest-recording](https://github.com/kiwicom/pytest-recording) to the projet
- [ ] Create all necessary cassettes for the current tests
- [ ] Refactor tests to fit in
- [ ] github action that launches tests on PRs and master branch

**Comment by vvaezian** [comment]
Thanks for the suggestion.
Related discussion [here](https://github.com/vvaezian/metabase_api_python/discussions/13#discussioncomment-2716224).
I'm more inclined toward a simpler solution. Maybe a Metabase JAR file with its associated H2 db which contains some cards built using the Sample dataset.

**Comment by vvaezian** [comment]
@Dynnammo  Fixed in v0.3.0.

**Comment by Dynnammo** [comment]
Warm thanks @vvaezian

**Comment by vvaezian** [comment]
Hi @Dynnammo,
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
